<<skip until matching line>>
Exception handling in test harness - string \[E\]
Error caught by Flutter test framework, thrown running a test.
Who lives, who dies, who tells your story\?
The test description was:
Exception handling in test harness - string
#0      main.<anonymous closure> \(.+[/\\]dev[/\\]automated_tests[/\\]flutter_test[/\\]exception_handling_test\.dart:10:5\)
<asynchronous suspension>
#1      .+ \(package:flutter_test[/\\]src[/\\]widget_tester\.dart:[0-9]+:[0-9]+\)
<<skip until matching line>>
\(elided [0-9]+ .+\)
<<skip until matching line>>
Exception handling in test harness - FlutterError \[E\]
Error caught by Flutter test framework, thrown running a test.
Who lives, who dies, who tells your story\?
The test description was:
Exception handling in test harness - FlutterError
#0      main.<anonymous closure> \(.+[/\\]dev[/\\]automated_tests[/\\]flutter_test[/\\]exception_handling_test\.dart:13:5\)
<asynchronous suspension>
#1      .+ \(package:flutter_test[/\\]src[/\\]widget_tester\.dart:[0-9]+:[0-9]+\)
<<skip until matching line>>
\(elided [0-9]+ .+\)
<<skip until matching line>>
Exception handling in test harness - uncaught Future error \[E\]
Error caught by Flutter test framework, thrown running a test.
Who lives, who dies, who tells your story\?
The test description was:
Exception handling in test harness - uncaught Future error
#[0-9]+ +main.<anonymous closure> \(.+[/\\]dev[/\\]automated_tests[/\\]flutter_test[/\\]exception_handling_test\.dart:16:9\)
#[0-9]+ +main.<anonymous closure> \(.+[/\\]dev[/\\]automated_tests[/\\]flutter_test[/\\]exception_handling_test\.dart:15:77\)
#[0-9]+ +.+ \(package:flutter_test[/\\]src[/\\]widget_tester\.dart:[0-9]+:[0-9]+\)
<<skip until matching line>>
\(elided [0-9]+ .+\)

.*..:.. \+0 -3: Some tests failed\. *
